name: swipetivity_app
version: 1.0.0+1
publish_to: none
description: The swipetivity app.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  json_annotation: ^4.8.1
  material_loading_buttons: ^1.1.0
  flutter_bloc: ^8.1.3
  go_router: ^13.1.0
  go_router_builder: ^2.4.1
  dart_mappable: ^4.2.0
  flutter_settings_ui: ^3.0.0
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0

dev_dependencies: 
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  dart_mappable_builder: ^4.2.0
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.7.1
  test: ^1.24.9

flutter: 
  uses-material-design: true

