spring:
  application:
    name: swipetivity-core
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/swipetivity
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  liquibase:
    change-log: classpath:db/changelog/master-changelog.xml
    database-change-log-table: database_changelog
    database-change-log-lock-table: database_changelog_lock
springdoc:
  api-docs:
    version: openapi_3_1
    enabled: false
  swagger-ui:
    path: /docs
    disable-swagger-default-url: true
    use-root-path: true